name: Deploy to GitHub Pages

on:
  push:
    branches: ['**'] # Trigger on all branches
  pull_request:
    branches: ['**'] # Also trigger on PRs to all branches

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests # Nuevo paso para ejecutar las pruebas
        run: npm test
      - name: Build
        run: npm run build
      - name: Setup Pages
        if: github.ref == 'refs/heads/main' # Only run for main branch
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: github.ref == 'refs/heads/main' # Only run for main branch
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Only run for main branch
        id: deployment
        uses: actions/deploy-pages@v4